# Generated by Django 5.1.1 on 2025-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achievement_achivementcat_cat_achivements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AchivementCat',
            new_name='AchievementCat',
        ),
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achivement',
            new_name='achievement',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='achivements',
        ),
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.achievement'),
        ),
    ]
